services:
  api-python:
    build:
      dockerfile: .devcontainer/api-python/Dockerfile
    command: sleep infinity
    ports:
      - ${API_PORT}:3000
    depends_on:
      - postgres
      - neo4j
    volumes:
      - .:/app-arch:cached
    environment:
      TZ: ${TZ}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      LOGGING_LEVEL: DEBUG
      POSTGRES_URI: postgresql://postgres:developer@postgres:5432/postgres
      NEO4J_URI: neo4j://neo4j:7687
      NEO4J_PASSWORD: developer

  api-rust:
    build:
      dockerfile: .devcontainer/api-rust/Dockerfile
    command: sleep infinity
    ports:
      - ${API2_PORT}:3000
    depends_on:
      - postgres
      - neo4j
    volumes:
      - .:/app-arch:cached
    environment:
      TZ: ${TZ}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      POSTGRES_URI: postgresql://postgres:developer@postgres:5432/postgres
      NEO4J_URI: neo4j://neo4j:7687
      NEO4J_PASSWORD: developer
      RUST_LOG: debug

  native-tauri:
    build:
      dockerfile: .devcontainer/native-tauri/Dockerfile
    command: sleep infinity
    depends_on:
      - api-python
      - api-rust
      - web-svelte
    volumes:
      - .:/app-arch:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/developer/.Xauthority:rw
    environment:
      TZ: ${TZ}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      RUST_LOG: debug
      # For GUI (including devices and security_opt)
      DISPLAY: ${DISPLAY}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      PULSE_SERVER: ${PULSE_SERVER}
    # devices:
    #   - /dev/dri:/dev/dri
    security_opt:
      - seccomp:unconfined

  web-svelte:
    build:
      dockerfile: .devcontainer/web-svelte/Dockerfile
    command: sleep infinity
    depends_on:
      - api-python
      - api-rust
    volumes:
      - .:/app-arch:cached
    environment:
      TZ: ${TZ}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      API_URL: http://localhost:${API_PORT}
      API2_URL: http://localhost:${API2_PORT}

  postgres:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: developer
    volumes:
      - postgres_data:/var/lib/postgresql/data
  neo4j:
    image: neo4j
    ports:
      - ${NEO4J_PORT}:7474
      - ${NEO4J_BOLT_PORT}:7687
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: neo4j/developer

volumes:
  postgres_data:
  neo4j_data:
