# https://github.com/jifalops/devcontainers/tree/main/images/python/.devcontainer
FROM jifalops/python:latest

# Install additional packages
RUN export DEBIAN_FRONTEND=noninteractive && sudo apt-get update && sudo apt-get install -y --no-install-recommends \
  trash-cli